### ISSUE TITLE
Update splash image

### ISSUE THREAD

**Issue by erikbrinkman** [postulate-ai/postulate-ai.github.io#2]
The splash image is just a placeholder, and you don't particularly like the pastels. This is to serve as a reminder to update it. Make sure to update the citation at the bottom / make sure that we're using an image we "have the rights" to.

**Comment by sarahfor** [comment]
Updated the Splash image to : Hero photo by [Milad Fakurian](https://unsplash.com/@fakurian?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash) on [Unsplash](https://unsplash.com/photos/blue-and-green-peacock-feather-58Z17lnVS4U?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash)
